import numpy as np
import pandas as pd
np.random.seed(42)
data = {
    'CustomerID': np.arange(1001, 1061),
    'OrderDate': pd.date_range(start='2025-01-01', periods=60),
    'Product': np.random.choice(['Laptop', 'Smartphone', 'Tablet', 'Monitor'], size=60),
    'Quantity': np.random.randint(1,5, size=60),
    'PricePerUnit': np.random.randint(100, 1000, size=60)
}

data['TotalAmount'] = data['Quantity']*data['PricePerUnit']
df = pd.DataFrame(data)
print('Sample Data:\n', df.head())

# What is the total revenue (sum of TotalAmount) generated by all transactions?
print('Total Revenue:',df['TotalAmount'].sum())

# Which product type had the highest average price per unit?
def highest_avg(dff)-> None:
    avg_sum_group = df.groupby('Product')['PricePerUnit'].mean()
    expensive_product = avg_sum_group.idxmax()
    highest_avg_price = avg_sum_group.max()
    print('Expensive Product', expensive_product)
    print('Hight Avg Price', round(highest_avg_price,2))

highest_avg(df)